name: cherry_8_runtime
description: The runtime of the Cherry8 console
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.38.5

dependencies:
  berry_lang: ^0.1.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
